// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tasty.Api.Data;

#nullable disable

namespace Tasty.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tasty.Api.Models.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("Tasty.Api.Models.KomentarRecept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Besedilo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Ocena")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("UporabnikId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.HasIndex("UporabnikId");

                    b.ToTable("KomentarjiReceptov");
                });

            modelBuilder.Entity("Tasty.Api.Models.KorakPriprave", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CasTrajanjaMin")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("ZaporednaStevilka")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("KorakiPriprave");
                });

            modelBuilder.Entity("Tasty.Api.Models.Oznaka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Oznake");
                });

            modelBuilder.Entity("Tasty.Api.Models.PriljubljenRecept", b =>
                {
                    b.Property<int>("UporabnikId")
                        .HasColumnType("int");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumDodano")
                        .HasColumnType("datetime2");

                    b.HasKey("UporabnikId", "ReceptId");

                    b.HasIndex("ReceptId");

                    b.ToTable("PriljubljeniRecepti");
                });

            modelBuilder.Entity("Tasty.Api.Models.Recept", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AvtorId")
                        .HasColumnType("int");

                    b.Property<int>("CasPripraveMin")
                        .HasColumnType("int");

                    b.Property<DateTime>("DatumUstvarjanja")
                        .HasColumnType("datetime2");

                    b.Property<bool>("JeJaven")
                        .HasColumnType("bit");

                    b.Property<string>("Naslov")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SteviloPorcij")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AvtorId");

                    b.ToTable("Recepti");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptKategorija", b =>
                {
                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId", "KategorijaId");

                    b.HasIndex("KategorijaId");

                    b.ToTable("ReceptKategorije");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptOznaka", b =>
                {
                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("OznakaId")
                        .HasColumnType("int");

                    b.HasKey("ReceptId", "OznakaId");

                    b.HasIndex("OznakaId");

                    b.ToTable("ReceptOznake");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptSestavina", b =>
                {
                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<int>("SestavinaId")
                        .HasColumnType("int");

                    b.Property<string>("Kolicina")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opomba")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReceptId", "SestavinaId");

                    b.HasIndex("SestavinaId");

                    b.ToTable("ReceptSestavine");
                });

            modelBuilder.Entity("Tasty.Api.Models.Sestavina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Sestavine");
                });

            modelBuilder.Entity("Tasty.Api.Models.SlikaRecepta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("JeNaslovna")
                        .HasColumnType("bit");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReceptId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReceptId");

                    b.ToTable("SlikeReceptov");
                });

            modelBuilder.Entity("Tasty.Api.Models.Uporabnik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DatumRegistracije")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GesloHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Uporabniki");
                });

            modelBuilder.Entity("Tasty.Api.Models.UporabnikVloga", b =>
                {
                    b.Property<int>("UporabnikId")
                        .HasColumnType("int");

                    b.Property<int>("VlogaId")
                        .HasColumnType("int");

                    b.HasKey("UporabnikId", "VlogaId");

                    b.HasIndex("VlogaId");

                    b.ToTable("UporabnikVloge");
                });

            modelBuilder.Entity("Tasty.Api.Models.Vloga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vloge");
                });

            modelBuilder.Entity("Tasty.Api.Models.KomentarRecept", b =>
                {
                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("Komentarji")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Uporabnik", "Uporabnik")
                        .WithMany("Komentarji")
                        .HasForeignKey("UporabnikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("Uporabnik");
                });

            modelBuilder.Entity("Tasty.Api.Models.KorakPriprave", b =>
                {
                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("KorakiPriprave")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("Tasty.Api.Models.PriljubljenRecept", b =>
                {
                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("PriljubljenOd")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Uporabnik", "Uporabnik")
                        .WithMany("PriljubljeniRecepti")
                        .HasForeignKey("UporabnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("Uporabnik");
                });

            modelBuilder.Entity("Tasty.Api.Models.Recept", b =>
                {
                    b.HasOne("Tasty.Api.Models.Uporabnik", "Avtor")
                        .WithMany("Recepti")
                        .HasForeignKey("AvtorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Avtor");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptKategorija", b =>
                {
                    b.HasOne("Tasty.Api.Models.Kategorija", "Kategorija")
                        .WithMany("Recepti")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("Kategorije")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptOznaka", b =>
                {
                    b.HasOne("Tasty.Api.Models.Oznaka", "Oznaka")
                        .WithMany("Recepti")
                        .HasForeignKey("OznakaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("Oznake")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Oznaka");

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("Tasty.Api.Models.ReceptSestavina", b =>
                {
                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("Sestavine")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Sestavina", "Sestavina")
                        .WithMany("Recepti")
                        .HasForeignKey("SestavinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");

                    b.Navigation("Sestavina");
                });

            modelBuilder.Entity("Tasty.Api.Models.SlikaRecepta", b =>
                {
                    b.HasOne("Tasty.Api.Models.Recept", "Recept")
                        .WithMany("Slike")
                        .HasForeignKey("ReceptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Recept");
                });

            modelBuilder.Entity("Tasty.Api.Models.UporabnikVloga", b =>
                {
                    b.HasOne("Tasty.Api.Models.Uporabnik", "Uporabnik")
                        .WithMany("UporabnikVloge")
                        .HasForeignKey("UporabnikId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tasty.Api.Models.Vloga", "Vloga")
                        .WithMany("UporabnikVloge")
                        .HasForeignKey("VlogaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Uporabnik");

                    b.Navigation("Vloga");
                });

            modelBuilder.Entity("Tasty.Api.Models.Kategorija", b =>
                {
                    b.Navigation("Recepti");
                });

            modelBuilder.Entity("Tasty.Api.Models.Oznaka", b =>
                {
                    b.Navigation("Recepti");
                });

            modelBuilder.Entity("Tasty.Api.Models.Recept", b =>
                {
                    b.Navigation("Kategorije");

                    b.Navigation("Komentarji");

                    b.Navigation("KorakiPriprave");

                    b.Navigation("Oznake");

                    b.Navigation("PriljubljenOd");

                    b.Navigation("Sestavine");

                    b.Navigation("Slike");
                });

            modelBuilder.Entity("Tasty.Api.Models.Sestavina", b =>
                {
                    b.Navigation("Recepti");
                });

            modelBuilder.Entity("Tasty.Api.Models.Uporabnik", b =>
                {
                    b.Navigation("Komentarji");

                    b.Navigation("PriljubljeniRecepti");

                    b.Navigation("Recepti");

                    b.Navigation("UporabnikVloge");
                });

            modelBuilder.Entity("Tasty.Api.Models.Vloga", b =>
                {
                    b.Navigation("UporabnikVloge");
                });
#pragma warning restore 612, 618
        }
    }
}
